### ISSUE TITLE
Add Custom Fonts (Font Family, Font Size, Chats Line Height, Letter Spacing)

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#22]
Enhance user experience and customization by enabling users to select custom fonts, including **font family** and **size**. Based on user feedback on social media, there are users who are not happy with the new ChatGPT font changes.

### Tasks:

- [x] Add a new section in the GPThemes settings or customization options titled `Font Styles` or just `Fonts`
- [x] Add dropdown menu for users to select their preferred **font family** from a list of available options (e.g., `Roboto`, `Inter`,  `Poppins` etc)
- [x] Add an number input field for users to specify their desired **font size** in `px` (convert this to `rem` and vice-versa)
- [x] Convert font-size `px` value from number input to `rem` and vice-versa
- [x]  Add an number input field for users to specify their desired **line heghts** in chats
- [x]  Add an number input field for users to specify their desired **letter spacing**
- [x] ~~Apply desired option live and immediately~~ This is removed. Changes are applied when the user unfocus the field.
- [x] Fetch the fonts from [Google Fonts](https://fonts.google.com/) by inserting the `<link>` in the `<head>` with the preferred fonts.
- [x] ! To ensure that there is no duplication of links injected in the head, first check if the desired Google Font has already been fetched. If the font has not been fetched, inject the necessary `<link>`, otherwise, skip the injection process. This will help maintain a clean and efficient code structure, while also improving performance by preventing unnecessary font fetching, thus minimizing spamming of requests.
- [x] Store the user's font preferences in their local storage to ensure that the selected fonts are applied consistently across the platform
- [x] Include a `Reset to default` option for users who wish to revert to the original font settings (reset all in once, or maybe add reset by each property)
- [x] Validate input fields to make sure they're not empty or not x>min and x<max
- [x] Display the errors when input values are wrong
- [x] Handle the values when there is an error...
