### ISSUE TITLE
Add `Canvas` support for Text and Code

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#86]
# TASKS
- [ ] #94 
- [x] Hide the GPThemes floating btn when Canvas is opened
- [x] #87
- [x] Chat Bubble: [`CodeMirror`](https://github.com/codemirror/codemirror5) editor bgs, active line, `Typing...` indicator, ...
- [x] #92 
- [x] Chat Bubble: Improve Canvas looking when there is only Canvas title
- [x] #88 
- [x] #89 
- [x] #91 
- [x] Enhance Canvas Header UI (title, buttons, `Run` and `Stop` code)
- [x] #93

## ⚠️ Known Issues:
The CodeMirror editor in the canvas feature fails to properly update its syntax highlighting when themes are changed using the GPThemes floating button. While the overall UI theme changes, the code highlighting remains in the previous theme's style, creating a visual inconsistency.
However, changing the theme via the ChatGPT settings correctly updates the CodeMirror syntax highlighting.

----

> ### [Canvas (Dec 10, 2024)](https://help.openai.com/en/articles/6825453-chatgpt-release-notes#h_72c532e4b9)
>Today we made Canvas available in 4o by default for all users, Free and Paid. Additionally, we launched a number of new capabilities for canvas, including:
>
> - **Canvas in GPTs**: Canvas can now be used with GPTs when enabled in the GPT creator. This toggle will be enabled for newly created GPTs by default.
> - **Python code execution:** You can now execute Python code in a canvas. ChatGPT will take a pass on fixing bugs in your code and provide comments on errors.
> - **Canvas shortcut:** You can now paste content into ChatGPT and instantly open it in canvas via a shortcut in the upper right corner of the composer.
> - **Canvas in Toolbox:** Canvas has been added as an option in the toolbox.
