### ISSUE TITLE
Improve `Canvas` floating edit buttons

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#88]
The current Canvas support layout, including the floating edit buttons on the bottom right, slider buttons, and submit buttons, needs to be improved to match the accent theme and provide better visual feedback for different states (e.g., edit mode, submit changes). The floating edit buttons should be styled to match the accent theme, and the slider buttons and submit buttons should have distinct styles to indicate whether the user is in edit mode or needs to submit changes.

- The floating edit buttons should be styled to match the accent theme.
- The slider/action buttons and submit buttons should have distinct styles to indicate whether the user is in edit mode or needs to submit changes.
- The user should be able to easily distinguish between different states (e.g., `Adjust the length` or `Reading level` in `ProseMirror`, `Port to a language` list buttons in `CodeMirror` vs submit changes).

## TASKS
- [x] Add different style for slider and for submit slider (action) change to know the states
- [x] Add background to mattch the accent and colorize the icons
- [x] Submit btn for main Canvas floating action button on bottom right 
- [x] Submit btn in Y-sliders
- [x] Differentiate primary floating bg and secondary (y-sliders wrapper)
- [x] Slider btns in `Adjust the length` and `Reading level` in `ProseMirror`
- [x] Improve `Port to a languege` and `Add emoji` list btns, add hover and active state style
- [x] Floating pause btn while processing: Add bg accent and color on-accent
