### ISSUE TITLE
Refactor and fix styling for all `[role="dialog"]` elements

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#95]
OpenAI's recent changes have modified the implementation of various UI elements to use `[role="dialog"]` and `popover`. This affects:

- Menu and submenu components
- Dialog windows
- Popup notifications
- Command palette interface ("`/`", "`@`" mentions)
- Search popup menu, etc

### Current Issues

- Inconsistent Styling: Existing CSS for `[role="dialog"]` no longer appropriately styles these elements since OpenAI moved various components to use this role
- Prompt Commands Code Scope: Command palette features ("`/`", "`@`" mentions) and search popup have been moved outside the prompt field in the background (code stucture)
- Empty Dialog Styling: Empty dialogs are receiving unwanted styling and excessive padding which creates unnecessary circular styling around the prompt textarea

### Risks

- Changes to dialog styling might affect other legitimate `[role="dialog"]` elements that should retain current styling
- Need to ensure backward compatibility with existing dialog implementations

### Tasks

- [x]  Audit all current uses of `[role="dialog"]` in the application
- [x]  Create new CSS selectors to differentiate between different types of dialogs (modal dialogs vs radix dialogs)
- [x]  Revert the style to all the `/`, `@`, autocomplete suggestion list etc
- [x]  Test changes across all affected components
- [x]  Verify no regression in existing dialog functionality
